Ensure proxy credentials file exists
I think adding this would fix the following bug:

$ voms-proxy-init --voms fedcloud.egi.eu --rfc
Enter GRID pass phrase for this identity:
Contacting voms1.egee.cesnet.cz:15002 [/DC=org/DC=terena/DC=tcs/OU=Domain Control Validated/CN=voms1.egee.cesnet.cz] "fedcloud.egi.eu"...
Error contacting voms1.egee.cesnet.cz:15002 for VO fedcloud.egi.eu: connect timed out
Error contacting voms1.egee.cesnet.cz:15002 for VO fedcloud.egi.eu: connect timed out
Error contacting voms1.egee.cesnet.cz:15002 for VO fedcloud.egi.eu: REST and legacy VOMS endpoints failed.
Contacting voms2.grid.cesnet.cz:15002 [/DC=org/DC=terena/DC=tcs/C=CZ/ST=Hlavni mesto Praha/L=Praha 6/O=CESNET/CN=voms2.grid.cesnet.cz] "fedcloud.egi.eu"...
Remote VOMS server contacted succesfully.

Error creating proxy certificate:  (No such file or directory)

But testing it in maven is not trivial, so untested...

with --debug

org.italiangrid.voms.VOMSError: Error creating proxy certificate:  (No such file or directory)
	at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.createProxy(DefaultVOMSProxyInitBehaviour.java:463)
	at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.initProxy(DefaultVOMSProxyInitBehaviour.java:202)
	at org.italiangrid.voms.clients.VomsProxyInit.execute(VomsProxyInit.java:307)
	at org.italiangrid.voms.clients.VomsProxyInit.<init>(VomsProxyInit.java:72)
	at org.italiangrid.voms.clients.VomsProxyInit.main(VomsProxyInit.java:56)
Caused by: java.io.FileNotFoundException:  (No such file or directory)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
	at org.italiangrid.voms.util.CredentialsUtils.saveProxyCredentials(CredentialsUtils.java:211)
	at org.italiangrid.voms.util.CredentialsUtils.saveProxyCredentials(CredentialsUtils.java:243)
	at org.italiangrid.voms.clients.impl.DefaultVOMSProxyInitBehaviour.createProxy(DefaultVOMSProxyInitBehaviour.java:456)
	... 4 more

ls /tmp/x509up_u1001
ls: cannot access /tmp/x509up_u1001: No such file or directory